### ISSUE TITLE
Feature request: Support alternator BatchGetItem metric

### ISSUE THREAD

**Issue by codingcuisg** [scylladb/scylla-grafana-monitoring#1550]
Please make sure that this is a feature request. 

**System information**
- Scylla version (you are using): 4.4.4
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Current scylla_alternator_operation only support
- GetItem
- PutItem
- UpdateItem
- DeleteItem
- BatchWriteItem
- Query
- Scan

Could we also have support for BatchGetItem? we have team using BatchGetItem function but not able to find the metric from alternator dashboard.

**Who will benefit with this feature?**
For the team which using BatchGetItem, it will help them identify the BatchGetItem related qps and latency.
**Any Other info.**
NA

**Comment by nyh** [comment]
Amazingly, this isn't just a Scylla Monitoring issue - the metric for BatchGetItem counts is missing in Scylla (the counter variable exists, but it's not exported!). I'll open an issue about that in the main Scylla repository.

**Comment by nyh** [comment]
@amnonh I just sent a patch to the Scylla mailing list to add the missing BatchGetItem sub-metric (it's a label inside the bigger `scylla_alternator_operation` metric) to Scylla. Will you also need to add it to the grafana dashboard et al., or will that happen automatically somehow?

**Comment by amnonh** [comment]
On Wed, Sep 29, 2021 at 3:20 PM nyh ***@***.***> wrote:

> @amnonh <https://github.com/amnonh> I just sent a patch to the Scylla
> mailing list to add the missing BatchGetItem sub-metric (it's a label
> inside the bigger scylla_alternator_operation metric) to Scylla. Will you
> also need to add it to the grafana dashboard et al., or will that happen
> automatically somehow?
>
I will need to do some minor change in the dashboard

**Comment by nyh** [comment]
@amnonh the Scylla patch reached master, so you'll now be able to add the missing operation to the dashboard.

**Comment by amnonh** [comment]
what scylla versions will this be part of?

**Comment by nyh** [comment]
We didn't backport it (yet?) so I guess 4.6?
Anyway, don't you have a "master" version, where you add the new features?

**Comment by amnonh** [comment]
for the last few releases we have unified templates for all versions, we
need to specify if a feature is available from a specific version

**Comment by amnonh** [comment]
@nyh what about enterprise? from what version will it be supported

**Comment by nyh** [comment]
@amnonh I don't know how/when we backport monitoring-related patches.  What do you recommend? Should I backport https://github.com/scylladb/scylla/issues/9406 to all living open-source branches (4.4-4.6), as we do for bugs?

Regarding the enterprise branch, I don't know, again, if this should be considered a bug. I also don't usually do those backports myself so I don't know how to answer. Maybe @eliransin can suggests what is the appropriate process for the enterprise branch (this bug tracker is the open-source repository, not the enterprise branch).

**Comment by amnonh** [comment]
@nyh I don't think you need to back port to open source, but that's only my opnion.
My question is practical, I need to know to what versions this is applicable, I'm trying not to put panels that don't report a metric.

**Comment by nyh** [comment]
I decided to backport to open-source 4.5 and 4.4 (it was already in 4.6). This was a real mistake, even if not a disastrous bug, and the fix is trivial and (hopefully) without risk.

By the way, it would have been really great if the monitoring stack could have fewer version-specific differences, and discover these differences automatically... In this case, the monitoring stack could somehow (I don't know how to do this in practice, I'm just suggesting an idea) discover that the BatchGetItem metric is completely missing and not show the panel - and then you can add it to all versions, and older versions it will simply be missing.

**Comment by amnonh** [comment]
> By the way, it would have been really great if the monitoring stack could have fewer version-specific differences, and discover these differences automatically... In this case, the monitoring stack could somehow (I don't know how to do this in practice, I'm just suggesting an idea) discover that the BatchGetItem metric is completely missing and not show the panel - and then you can add it to all versions, and older versions it will simply be missing.

I agree and I do that when possible, in this case it hit some Grafana bugs/limitations so it's the best we can do
