### ISSUE TITLE
Manager Dashboard: add progress of the restore process

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-grafana-monitoring#1960]
Manager 3.1 add a restore process and expose new metrics to show the restore process.
It would be useful to expose these metrics in the Manager dashboard:
- percent per restore completed
- numbers of TB restored so far

**Comment by tzach** [comment]
@karol-kokoszka please add the relevant metric names

**Comment by karol-kokoszka** [comment]
@tzach we don't have percentage metric. We can introduce that, but maybe in 3.1.1 ?

> numbers of TB restored so far

We have metric that shows how much data is still yet to be restored instead of metric showing how much of the data is restored already.

**Comment by amnonh** [comment]
@karol-kokoszka I can add the remaining data panel, I guess it's better than nothing, mainly for debugging purposes, but it's not very informative.
From a user perspective, they care about how far we are with the restore process, absolute bytes count does not give much.

**Comment by karol-kokoszka** [comment]
OK, then let's use remaining_bytes for now.
We will introduce percentage metric in the next release.

**Comment by amnonh** [comment]
@tzach is that any different than #1946 ? if not, it split the conversation
